title: Preprint Review Metadata Modelling
description: A collection of metadata models for preprint reviews
baseurl: "/preprint-review-metadata"
url: "https://themarkness.github.io"

# Bluesky configuration
bluesky_handle: mark2d2.bsky.social

# Build settings
theme: minima
markdown: kramdown
